/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/feed-service';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from 'ionic-angular/components/menu/menu';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from 'ionic-angular/components/list/list';
import * as import17 from 'ionic-angular/components/item/item';
import * as import18 from 'ionic-angular/components/icon/icon';
import * as import19 from 'ionic-angular/components/menu/menu-close';
import * as import20 from 'ionic-angular/components/label/label';
import * as import21 from 'ionic-angular/components/toggle/toggle';
import * as import22 from 'ionic-angular/components/nav/nav';
import * as import23 from '../../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import24 from 'ionic-angular/components/menu/menu-controller';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from 'ionic-angular/platform/platform';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from '../../node_modules/ionic-angular/components/toggle/toggle.ngfactory';
import * as import38 from 'ionic-angular/util/haptic';
import * as import39 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import40 from 'ionic-angular/navigation/nav-controller-base';
import * as import41 from '@angular/core/src/linker/component_factory_resolver';
import * as import42 from 'ionic-angular/transitions/transition-controller';
import * as import43 from 'ionic-angular/navigation/deep-linker';
import * as import44 from '@angular/forms/src/directives/control_value_accessor';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FeedService),this.parentInjector.get(import10.AlertController));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import12.ComponentFactory<import3.HomePage> = new import12.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _viewQuery_Nav_0:import13.QueryList<any>;
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _Menu_1_4:import14.Menu;
  _query_Content_1_0:import13.QueryList<any>;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Content_4_4:import15.Content;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _List_7_3:import16.List;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Item_9_4:import17.Item;
  _ItemContent_9_5:import17.ItemContent;
  _query_Label_9_0:import13.QueryList<any>;
  _query_Button_9_1:import13.QueryList<any>;
  _query_Icon_9_2:import13.QueryList<any>;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _Icon_12_3:import18.Icon;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _Item_16_4:import17.Item;
  _ItemContent_16_5:import17.ItemContent;
  _query_Label_16_0:import13.QueryList<any>;
  _query_Button_16_1:import13.QueryList<any>;
  _query_Icon_16_2:import13.QueryList<any>;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _Icon_19_3:import18.Icon;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import17.Item;
  _ItemContent_23_5:import17.ItemContent;
  _query_Label_23_0:import13.QueryList<any>;
  _query_Button_23_1:import13.QueryList<any>;
  _query_Icon_23_2:import13.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _Icon_26_3:import18.Icon;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Item_30_4:import17.Item;
  _ItemContent_30_5:import17.ItemContent;
  _MenuClose_30_6:import19.MenuClose;
  _query_Label_30_0:import13.QueryList<any>;
  _query_Button_30_1:import13.QueryList<any>;
  _query_Icon_30_2:import13.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _Icon_33_3:import18.Icon;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _Item_37_4:import17.Item;
  _ItemContent_37_5:import17.ItemContent;
  _MenuClose_37_6:import19.MenuClose;
  _query_Label_37_0:import13.QueryList<any>;
  _query_Button_37_1:import13.QueryList<any>;
  _query_Icon_37_2:import13.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _el_40:any;
  _Icon_40_3:import18.Icon;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import2.AppElement;
  _Item_44_4:import17.Item;
  _ItemContent_44_5:import17.ItemContent;
  _MenuClose_44_6:import19.MenuClose;
  _query_Label_44_0:import13.QueryList<any>;
  _query_Button_44_1:import13.QueryList<any>;
  _query_Icon_44_2:import13.QueryList<any>;
  _text_45:any;
  _el_46:any;
  _el_47:any;
  _Icon_47_3:import18.Icon;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import2.AppElement;
  _Item_51_4:import17.Item;
  _ItemContent_51_5:import17.ItemContent;
  _query_Label_51_0:import13.QueryList<any>;
  _query_Button_51_1:import13.QueryList<any>;
  _query_Icon_51_2:import13.QueryList<any>;
  _text_52:any;
  _el_53:any;
  _Label_53_3:import20.Label;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import2.AppElement;
  _Toggle_57_4:import21.Toggle;
  __NG_VALUE_ACCESSOR_57_5:any[];
  _text_58:any;
  _text_59:any;
  _el_60:any;
  /*private*/ _appEl_60:import2.AppElement;
  _Item_60_4:import17.Item;
  _ItemContent_60_5:import17.ItemContent;
  _query_Label_60_0:import13.QueryList<any>;
  _query_Button_60_1:import13.QueryList<any>;
  _query_Icon_60_2:import13.QueryList<any>;
  _text_61:any;
  _el_62:any;
  _Label_62_3:import20.Label;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import2.AppElement;
  _Toggle_66_4:import21.Toggle;
  __NG_VALUE_ACCESSOR_66_5:any[];
  _text_67:any;
  _text_68:any;
  _el_69:any;
  /*private*/ _appEl_69:import2.AppElement;
  _Item_69_4:import17.Item;
  _ItemContent_69_5:import17.ItemContent;
  _query_Label_69_0:import13.QueryList<any>;
  _query_Button_69_1:import13.QueryList<any>;
  _query_Icon_69_2:import13.QueryList<any>;
  _text_70:any;
  _el_71:any;
  _Label_71_3:import20.Label;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  /*private*/ _appEl_76:import2.AppElement;
  _Toggle_76_4:import21.Toggle;
  __NG_VALUE_ACCESSOR_76_5:any[];
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  /*private*/ _appEl_83:import2.AppElement;
  _Nav_83_4:import22.Nav;
  _text_84:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_57_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_57_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_57_5 = [this._Toggle_57_4]); }
    return this.__NG_VALUE_ACCESSOR_57_5;
  }
  get _NG_VALUE_ACCESSOR_66_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_66_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_66_5 = [this._Toggle_66_4]); }
    return this.__NG_VALUE_ACCESSOR_66_5;
  }
  get _NG_VALUE_ACCESSOR_76_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_76_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_76_5 = [this._Toggle_76_4]); }
    return this.__NG_VALUE_ACCESSOR_76_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import13.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_1,'role','navigation');
    this.renderer.setElementAttribute(this._el_1,'side','right');
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import23.viewFactory_Menu0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Menu_1_4 = new import14.Menu(this.parentInjector.get(import24.MenuController),new import25.ElementRef(this._el_1),this.parentInjector.get(import26.Config),this.parentInjector.get(import27.Platform),this.renderer,this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import30.GestureController));
    this._query_Content_1_0 = new import13.QueryList<any>();
    this._appEl_1.initComponent(this._Menu_1_4,[],compView_1);
    this._text_2 = this.renderer.createText((null as any),' ',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_4 = new import2.AppElement(4,1,this,this._el_4);
    var compView_4:any = import31.viewFactory_Content0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Content_4_4 = new import15.Content(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_4.initComponent(this._Content_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),' ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n\n\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_7_3 = new import16.List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','item item-block');
    this.renderer.setElementAttribute(this._el_9,'icon-left','');
    this.renderer.setElementAttribute(this._el_9,'ion-item','');
    this.renderer.setElementAttribute(this._el_9,'item-right','');
    this.renderer.setElementAttribute(this._el_9,'onclick','window.open(\'http://www.der-postillon.com/\', \'_system\', \'location=yes\');');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import35.viewFactory_Item0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Item_9_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_9),this.renderer);
    this._ItemContent_9_5 = new import17.ItemContent();
    this._query_Label_9_0 = new import13.QueryList<any>();
    this._query_Button_9_1 = new import13.QueryList<any>();
    this._query_Icon_9_2 = new import13.QueryList<any>();
    this._appEl_9.initComponent(this._Item_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h3',(null as any));
    this._el_12 = this.renderer.createElement(this._el_11,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_12,'name','globe');
    this.renderer.setElementAttribute(this._el_12,'role','img');
    this._Icon_12_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText(this._el_11,' Postillon.com',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_9_0.reset([]);
    this._Item_9_4.contentLabel = this._query_Label_9_0.first;
    compView_9.create(this._Item_9_4,[
      [],
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_14
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','item item-block');
    this.renderer.setElementAttribute(this._el_16,'icon-left','');
    this.renderer.setElementAttribute(this._el_16,'ion-item','');
    this.renderer.setElementAttribute(this._el_16,'item-right','');
    this.renderer.setElementAttribute(this._el_16,'onclick','window.open(\'https://www.facebook.com/DerPostillon\', \'_system\', \'location=yes\');');
    this._appEl_16 = new import2.AppElement(16,7,this,this._el_16);
    var compView_16:any = import35.viewFactory_Item0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Item_16_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_16),this.renderer);
    this._ItemContent_16_5 = new import17.ItemContent();
    this._query_Label_16_0 = new import13.QueryList<any>();
    this._query_Button_16_1 = new import13.QueryList<any>();
    this._query_Icon_16_2 = new import13.QueryList<any>();
    this._appEl_16.initComponent(this._Item_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'h3',(null as any));
    this._el_19 = this.renderer.createElement(this._el_18,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_19,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_19,'role','img');
    this._Icon_19_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_18,' Auf Facebook folgen',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_16_0.reset([]);
    this._Item_16_4.contentLabel = this._query_Label_16_0.first;
    compView_16.create(this._Item_16_4,[
      [],
      [],
      [].concat([
        this._text_17,
        this._el_18,
        this._text_21
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this.renderer.setElementAttribute(this._el_23,'icon-left','');
    this.renderer.setElementAttribute(this._el_23,'ion-item','');
    this.renderer.setElementAttribute(this._el_23,'item-right','');
    this.renderer.setElementAttribute(this._el_23,'onclick','window.open(\'https://plus.google.com/u/0/+postillon\', \'_system\', \'location=yes\');');
    this._appEl_23 = new import2.AppElement(23,7,this,this._el_23);
    var compView_23:any = import35.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import17.ItemContent();
    this._query_Label_23_0 = new import13.QueryList<any>();
    this._query_Button_23_1 = new import13.QueryList<any>();
    this._query_Icon_23_2 = new import13.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'h3',(null as any));
    this._el_26 = this.renderer.createElement(this._el_25,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_26,'name','logo-googleplus');
    this.renderer.setElementAttribute(this._el_26,'role','img');
    this._Icon_26_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText(this._el_25,' Auf Google+ folgen',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [],
      [],
      [].concat([
        this._text_24,
        this._el_25,
        this._text_28
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','item item-block');
    this.renderer.setElementAttribute(this._el_30,'icon-left','');
    this.renderer.setElementAttribute(this._el_30,'ion-item','');
    this.renderer.setElementAttribute(this._el_30,'item-right','');
    this.renderer.setElementAttribute(this._el_30,'menuClose','');
    this.renderer.setElementAttribute(this._el_30,'onclick','window.open(\'http://www.der-postillon.com/p/den-postillon-unterstutzen.html\', \'_system\', \'location=yes\');');
    this._appEl_30 = new import2.AppElement(30,7,this,this._el_30);
    var compView_30:any = import35.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Item_30_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_30),this.renderer);
    this._ItemContent_30_5 = new import17.ItemContent();
    this._MenuClose_30_6 = new import19.MenuClose(this.parentInjector.get(import24.MenuController));
    this._query_Label_30_0 = new import13.QueryList<any>();
    this._query_Button_30_1 = new import13.QueryList<any>();
    this._query_Icon_30_2 = new import13.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'h3',(null as any));
    this._el_33 = this.renderer.createElement(this._el_32,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_33,'name','logo-euro');
    this.renderer.setElementAttribute(this._el_33,'role','img');
    this._Icon_33_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText(this._el_32,' Postillon unterstützen',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_30_0.reset([]);
    this._Item_30_4.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_4,[
      [],
      [],
      [].concat([
        this._text_31,
        this._el_32,
        this._text_35
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_36 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','item item-block');
    this.renderer.setElementAttribute(this._el_37,'icon-left','');
    this.renderer.setElementAttribute(this._el_37,'ion-item','');
    this.renderer.setElementAttribute(this._el_37,'item-right','');
    this.renderer.setElementAttribute(this._el_37,'menuClose','');
    this._appEl_37 = new import2.AppElement(37,7,this,this._el_37);
    var compView_37:any = import35.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Item_37_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_37),this.renderer);
    this._ItemContent_37_5 = new import17.ItemContent();
    this._MenuClose_37_6 = new import19.MenuClose(this.parentInjector.get(import24.MenuController));
    this._query_Label_37_0 = new import13.QueryList<any>();
    this._query_Button_37_1 = new import13.QueryList<any>();
    this._query_Icon_37_2 = new import13.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_4,[],compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'h3',(null as any));
    this._el_40 = this.renderer.createElement(this._el_39,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_40,'name','thumbs-up');
    this.renderer.setElementAttribute(this._el_40,'role','img');
    this._Icon_40_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText(this._el_39,' App bewerten',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_37_0.reset([]);
    this._Item_37_4.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_4,[
      [],
      [],
      [].concat([
        this._text_38,
        this._el_39,
        this._text_42
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','item item-block');
    this.renderer.setElementAttribute(this._el_44,'icon-left','');
    this.renderer.setElementAttribute(this._el_44,'ion-item','');
    this.renderer.setElementAttribute(this._el_44,'item-right','');
    this.renderer.setElementAttribute(this._el_44,'menuClose','');
    this.renderer.setElementAttribute(this._el_44,'onclick','window.open(\'http://www.der-postillon.com/p/uber-den-postillon.html\', \'_system\', \'location=yes\');');
    this._appEl_44 = new import2.AppElement(44,7,this,this._el_44);
    var compView_44:any = import35.viewFactory_Item0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Item_44_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_44),this.renderer);
    this._ItemContent_44_5 = new import17.ItemContent();
    this._MenuClose_44_6 = new import19.MenuClose(this.parentInjector.get(import24.MenuController));
    this._query_Label_44_0 = new import13.QueryList<any>();
    this._query_Button_44_1 = new import13.QueryList<any>();
    this._query_Icon_44_2 = new import13.QueryList<any>();
    this._appEl_44.initComponent(this._Item_44_4,[],compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'h3',(null as any));
    this._el_47 = this.renderer.createElement(this._el_46,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_47,'name','information-circle');
    this.renderer.setElementAttribute(this._el_47,'role','img');
    this._Icon_47_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_47),this.renderer);
    this._text_48 = this.renderer.createText(this._el_46,' Impressum',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_44_0.reset([]);
    this._Item_44_4.contentLabel = this._query_Label_44_0.first;
    compView_44.create(this._Item_44_4,[
      [],
      [],
      [].concat([
        this._text_45,
        this._el_46,
        this._text_49
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_50 = this.renderer.createText(this._el_7,'\n\n\n      ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_7,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','item item-block');
    this._appEl_51 = new import2.AppElement(51,7,this,this._el_51);
    var compView_51:any = import35.viewFactory_Item0(this.viewUtils,this.injector(51),this._appEl_51);
    this._Item_51_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_51),this.renderer);
    this._ItemContent_51_5 = new import17.ItemContent();
    this._query_Label_51_0 = new import13.QueryList<any>();
    this._query_Button_51_1 = new import13.QueryList<any>();
    this._query_Icon_51_2 = new import13.QueryList<any>();
    this._appEl_51.initComponent(this._Item_51_4,[],compView_51);
    this._text_52 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_53_3 = new import20.Label(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_53),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._el_54 = this.renderer.createElement(this._el_53,'h3',(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Bilder laden',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_57 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_57,'checked','true');
    this._appEl_57 = new import2.AppElement(57,51,this,this._el_57);
    var compView_57:any = import37.viewFactory_Toggle0(this.viewUtils,this.injector(57),this._appEl_57);
    this._Toggle_57_4 = new import21.Toggle(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_57),this.renderer,this.parentInjector.get(import38.Haptic),this._Item_51_4);
    this._appEl_57.initComponent(this._Toggle_57_4,[],compView_57);
    compView_57.create(this._Toggle_57_4,[],(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_51_0.reset([this._Label_53_3]);
    this._Item_51_4.contentLabel = this._query_Label_51_0.first;
    compView_51.create(this._Item_51_4,[
      [],
      [].concat([this._el_53]),
      [].concat([
        this._text_52,
        this._text_56,
        this._text_58
      ]
      ),
      [],
      [].concat([this._el_57])
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(this._el_7,'\n\n      ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_7,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','item item-block');
    this._appEl_60 = new import2.AppElement(60,7,this,this._el_60);
    var compView_60:any = import35.viewFactory_Item0(this.viewUtils,this.injector(60),this._appEl_60);
    this._Item_60_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_60),this.renderer);
    this._ItemContent_60_5 = new import17.ItemContent();
    this._query_Label_60_0 = new import13.QueryList<any>();
    this._query_Button_60_1 = new import13.QueryList<any>();
    this._query_Icon_60_2 = new import13.QueryList<any>();
    this._appEl_60.initComponent(this._Item_60_4,[],compView_60);
    this._text_61 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_62_3 = new import20.Label(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_62),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._el_63 = this.renderer.createElement(this._el_62,'h3',(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Dyn. Themewechsel',(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_66 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_66,'checked','true');
    this._appEl_66 = new import2.AppElement(66,60,this,this._el_66);
    var compView_66:any = import37.viewFactory_Toggle0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Toggle_66_4 = new import21.Toggle(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_66),this.renderer,this.parentInjector.get(import38.Haptic),this._Item_60_4);
    this._appEl_66.initComponent(this._Toggle_66_4,[],compView_66);
    compView_66.create(this._Toggle_66_4,[],(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_60_0.reset([this._Label_62_3]);
    this._Item_60_4.contentLabel = this._query_Label_60_0.first;
    compView_60.create(this._Item_60_4,[
      [],
      [].concat([this._el_62]),
      [].concat([
        this._text_61,
        this._text_65,
        this._text_67
      ]
      ),
      [],
      [].concat([this._el_66])
    ]
    ,(null as any));
    this._text_68 = this.renderer.createText(this._el_7,'\n\n      ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_7,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','item item-block');
    this._appEl_69 = new import2.AppElement(69,7,this,this._el_69);
    var compView_69:any = import35.viewFactory_Item0(this.viewUtils,this.injector(69),this._appEl_69);
    this._Item_69_4 = new import17.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_69),this.renderer);
    this._ItemContent_69_5 = new import17.ItemContent();
    this._query_Label_69_0 = new import13.QueryList<any>();
    this._query_Button_69_1 = new import13.QueryList<any>();
    this._query_Icon_69_2 = new import13.QueryList<any>();
    this._appEl_69.initComponent(this._Item_69_4,[],compView_69);
    this._text_70 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_71_3 = new import20.Label(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_71),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._el_72 = this.renderer.createElement(this._el_71,'h3',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Pandasexualaktivität',(null as any));
    this._text_74 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_75 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_76 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_76,'checked','true');
    this.renderer.setElementAttribute(this._el_76,'color','secondary');
    this._appEl_76 = new import2.AppElement(76,69,this,this._el_76);
    var compView_76:any = import37.viewFactory_Toggle0(this.viewUtils,this.injector(76),this._appEl_76);
    this._Toggle_76_4 = new import21.Toggle(this.parentInjector.get(import36.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_76),this.renderer,this.parentInjector.get(import38.Haptic),this._Item_69_4);
    this._appEl_76.initComponent(this._Toggle_76_4,[],compView_76);
    compView_76.create(this._Toggle_76_4,[],(null as any));
    this._text_77 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_69_0.reset([this._Label_71_3]);
    this._Item_69_4.contentLabel = this._query_Label_69_0.first;
    compView_69.create(this._Item_69_4,[
      [],
      [].concat([this._el_71]),
      [].concat([
        this._text_70,
        this._text_74,
        this._text_75,
        this._text_77
      ]
      ),
      [],
      [].concat([this._el_76])
    ]
    ,(null as any));
    this._text_78 = this.renderer.createText(this._el_7,'\n',(null as any));
    this._text_79 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_80 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    compView_4.create(this._Content_4_4,[
      [],
      [].concat([
        this._text_5,
        this._text_6,
        this._el_7,
        this._text_80
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_81 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_1_0.reset([this._Content_4_4]);
    this._Menu_1_4.menuContent = this._query_Content_1_0.first;
      compView_1.create(this._Menu_1_4,[[].concat([
        this._text_2,
        this._text_3,
        this._el_4,
        this._text_81
      ]
    )],(null as any));
    this._text_82 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_83 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_83,'swipeBackEnabled','false');
    this._appEl_83 = new import2.AppElement(83,(null as any),this,this._el_83);
    var compView_83:any = import39.viewFactory_Nav0(this.viewUtils,this.injector(83),this._appEl_83);
    this._Nav_83_4 = new import22.Nav(this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import40.NavControllerBase,(null as any)),this.parentInjector.get(import32.App),this.parentInjector.get(import26.Config),this.parentInjector.get(import28.Keyboard),new import25.ElementRef(this._el_83),this.parentInjector.get(import29.NgZone),this.renderer,this.parentInjector.get(import41.ComponentFactoryResolver),this.parentInjector.get(import30.GestureController),this.parentInjector.get(import42.TransitionController),this.parentInjector.get(import43.DeepLinker,(null as any)));
    this._appEl_83.initComponent(this._Nav_83_4,[],compView_83);
    compView_83.create(this._Nav_83_4,[],(null as any));
    this._text_84 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_83_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Icon) && (12 === requestNodeIndex))) { return this._Icon_12_3; }
    if (((token === import17.Item) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_9_4; }
    if (((token === import17.ItemContent) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_9_5; }
    if (((token === import18.Icon) && (19 === requestNodeIndex))) { return this._Icon_19_3; }
    if (((token === import17.Item) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_16_4; }
    if (((token === import17.ItemContent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_16_5; }
    if (((token === import18.Icon) && (26 === requestNodeIndex))) { return this._Icon_26_3; }
    if (((token === import17.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_23_4; }
    if (((token === import17.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_23_5; }
    if (((token === import18.Icon) && (33 === requestNodeIndex))) { return this._Icon_33_3; }
    if (((token === import17.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Item_30_4; }
    if (((token === import17.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ItemContent_30_5; }
    if (((token === import19.MenuClose) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._MenuClose_30_6; }
    if (((token === import18.Icon) && (40 === requestNodeIndex))) { return this._Icon_40_3; }
    if (((token === import17.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_37_4; }
    if (((token === import17.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ItemContent_37_5; }
    if (((token === import19.MenuClose) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._MenuClose_37_6; }
    if (((token === import18.Icon) && (47 === requestNodeIndex))) { return this._Icon_47_3; }
    if (((token === import17.Item) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Item_44_4; }
    if (((token === import17.ItemContent) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ItemContent_44_5; }
    if (((token === import19.MenuClose) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._MenuClose_44_6; }
    if (((token === import20.Label) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Label_53_3; }
    if (((token === import21.Toggle) && (57 === requestNodeIndex))) { return this._Toggle_57_4; }
    if (((token === import44.NG_VALUE_ACCESSOR) && (57 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_57_5; }
    if (((token === import17.Item) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Item_51_4; }
    if (((token === import17.ItemContent) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ItemContent_51_5; }
    if (((token === import20.Label) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Label_62_3; }
    if (((token === import21.Toggle) && (66 === requestNodeIndex))) { return this._Toggle_66_4; }
    if (((token === import44.NG_VALUE_ACCESSOR) && (66 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_66_5; }
    if (((token === import17.Item) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Item_60_4; }
    if (((token === import17.ItemContent) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._ItemContent_60_5; }
    if (((token === import20.Label) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Label_71_3; }
    if (((token === import21.Toggle) && (76 === requestNodeIndex))) { return this._Toggle_76_4; }
    if (((token === import44.NG_VALUE_ACCESSOR) && (76 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_76_5; }
    if (((token === import17.Item) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._Item_69_4; }
    if (((token === import17.ItemContent) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._ItemContent_69_5; }
    if (((token === import16.List) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._List_7_3; }
    if (((token === import15.Content) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._Content_4_4; }
    if (((token === import14.Menu) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Menu_1_4; }
    if (((token === import22.Nav) && (83 === requestNodeIndex))) { return this._Nav_83_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_0:any = this._Nav_83_4;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_1_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'right';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Menu_1_4.side = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_1.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_1_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_4_4.ngOnInit(); }
    const currVal_3:any = 'globe';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_12_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'logo-facebook';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_19_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = 'logo-googleplus';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_26_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._MenuClose_30_6.menuClose = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = 'logo-euro';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Icon_33_3.name = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._MenuClose_37_6.menuClose = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'thumbs-up';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Icon_40_3.name = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_18:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._MenuClose_44_6.menuClose = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'information-circle';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Icon_47_3.name = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_21:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._Toggle_57_4.checked = currVal_21;
      this._expr_21 = currVal_21;
    }
    const currVal_23:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._Toggle_66_4.checked = currVal_23;
      this._expr_23 = currVal_23;
    }
    const currVal_25:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._Toggle_76_4.color = currVal_25;
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._Toggle_76_4.checked = currVal_26;
      this._expr_26 = currVal_26;
    }
    const currVal_28:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._Nav_83_4.root = currVal_28;
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = 'false';
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._Nav_83_4.swipeBackEnabled = currVal_29;
      this._expr_29 = currVal_29;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_9_1.dirty) {
        this._query_Button_9_1.reset([]);
        this._Item_9_4._buttons = this._query_Button_9_1;
        this._query_Button_9_1.notifyOnChanges();
      }
      if (this._query_Icon_9_2.dirty) {
        this._query_Icon_9_2.reset([this._Icon_12_3]);
        this._Item_9_4._icons = this._query_Icon_9_2;
        this._query_Icon_9_2.notifyOnChanges();
      }
      if (this._query_Button_16_1.dirty) {
        this._query_Button_16_1.reset([]);
        this._Item_16_4._buttons = this._query_Button_16_1;
        this._query_Button_16_1.notifyOnChanges();
      }
      if (this._query_Icon_16_2.dirty) {
        this._query_Icon_16_2.reset([this._Icon_19_3]);
        this._Item_16_4._icons = this._query_Icon_16_2;
        this._query_Icon_16_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([this._Icon_26_3]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset([]);
        this._Item_30_4._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset([this._Icon_33_3]);
        this._Item_30_4._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset([]);
        this._Item_37_4._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset([this._Icon_40_3]);
        this._Item_37_4._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      if (this._query_Button_44_1.dirty) {
        this._query_Button_44_1.reset([]);
        this._Item_44_4._buttons = this._query_Button_44_1;
        this._query_Button_44_1.notifyOnChanges();
      }
      if (this._query_Icon_44_2.dirty) {
        this._query_Icon_44_2.reset([this._Icon_47_3]);
        this._Item_44_4._icons = this._query_Icon_44_2;
        this._query_Icon_44_2.notifyOnChanges();
      }
      if (this._query_Button_51_1.dirty) {
        this._query_Button_51_1.reset([]);
        this._Item_51_4._buttons = this._query_Button_51_1;
        this._query_Button_51_1.notifyOnChanges();
      }
      if (this._query_Icon_51_2.dirty) {
        this._query_Icon_51_2.reset([]);
        this._Item_51_4._icons = this._query_Icon_51_2;
        this._query_Icon_51_2.notifyOnChanges();
      }
      if (this._query_Button_60_1.dirty) {
        this._query_Button_60_1.reset([]);
        this._Item_60_4._buttons = this._query_Button_60_1;
        this._query_Button_60_1.notifyOnChanges();
      }
      if (this._query_Icon_60_2.dirty) {
        this._query_Icon_60_2.reset([]);
        this._Item_60_4._icons = this._query_Icon_60_2;
        this._query_Icon_60_2.notifyOnChanges();
      }
      if (this._query_Button_69_1.dirty) {
        this._query_Button_69_1.reset([]);
        this._Item_69_4._buttons = this._query_Button_69_1;
        this._query_Button_69_1.notifyOnChanges();
      }
      if (this._query_Icon_69_2.dirty) {
        this._query_Icon_69_2.reset([]);
        this._Item_69_4._icons = this._query_Icon_69_2;
        this._query_Icon_69_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_9_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_16_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_30_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_37_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_44_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_57_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_51_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_66_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_60_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_76_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_69_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Content_4_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_4,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_12_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_12,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_19_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_19,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_8:any = this._Icon_26_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_26,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = this._Icon_33_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_33,'hide',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = this._Icon_40_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_40,'hide',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_20:any = this._Icon_47_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_47,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_22:any = this._Toggle_57_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_57,'toggle-disabled',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:any = this._Toggle_66_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_66,'toggle-disabled',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._Toggle_76_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_76,'toggle-disabled',currVal_27);
      this._expr_27 = currVal_27;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_83_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_12_3.ngOnDestroy();
    this._Icon_19_3.ngOnDestroy();
    this._Icon_26_3.ngOnDestroy();
    this._Icon_33_3.ngOnDestroy();
    this._Icon_40_3.ngOnDestroy();
    this._Icon_47_3.ngOnDestroy();
    this._Toggle_57_4.ngOnDestroy();
    this._Toggle_66_4.ngOnDestroy();
    this._Toggle_76_4.ngOnDestroy();
    this._Content_4_4.ngOnDestroy();
    this._Menu_1_4.ngOnDestroy();
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuClose_30_6.close()) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuClose_37_6.close()) !== false);
    return (true && pd_0);
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuClose_44_6.close()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('D:/_WebProjects/_Detzler_App_Postillion_RSS/blank-rss-postillon-ionic2/.tmp/pages/home/home.html',0,import11.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}